# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5df911571f3720ca7170f6f538cc8c4d212f14154c850e3436d366ccbcec564dab32e9a1c7fc5607f844005e1c6d524e62ed99940c10fb21fc5e5791cef9633f

test:
  secret_key_base: da8eb669717c8abe876b275cfeee6645e405af0e2dadfe4ef6a451dbb0608f8244de4b031199cdcff03de9db0321fb56c7958e80dcfc5f01ad83f9a288d48ba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
